site_name: DSMRlogger2HTTP
site_url: https://willem.aandewiel.nl/index.php/2018/08/28/slimme-meter-uitlezer/
site_description: Project documentation with mkdocs.
site_author: Willem Aandewiel

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml

nav:
    - 'index.md'

    - bouwbeschrijving: 'bouwbeschrijvingV3.md'

    - Installatie ArduinoIDE: 'installatieArduinoIDE.md'

    - Installatie Bibliotheken: 'installatieBibliotheken.md'

    - Firmware:
       - 'Clonen van github': 'clonenFirmware.md'
       - 'Uploaden naar ESP-01': 'uploadenFirmware.md'
       - 'Upload Data ESP-01': 'uploadenDataMap.md'

    - Verschillen ESP-01 modules': 'verschillenESP01ESP01S.md'

